services:
  app:
    container_name: vim-slime_matplotlib-bug
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../nvim:/root/.config/nvim 
      - ..:/workspace
    working_dir: /workspace